- name: download github cli gpg key
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'

- name: get dpkg architecture
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: add github cli apt repository
  apt_repository:
    repo: "deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    filename: github-cli

- name: install gh
  apt:
    name: gh
    state: latest
    update_cache: true

- name: check gh auth status
  command: gh auth status
  register: gh_auth
  changed_when: false
  failed_when: false
  become: false

- name: manage gh extensions
  when: gh_auth.rc == 0
  become: false
  block:
    - name: check installed gh extensions
      shell: gh extension list | grep act
      register: gh_extensions
      changed_when: false
      failed_when: false

    - name: get latest gh-act release tag
      uri:
        url: https://api.github.com/repos/nektos/gh-act/releases/latest
      register: gh_act_release

    - name: install gh-act extension
      command: gh extension install nektos/gh-act
      changed_when: true
      when: "'nektos/gh-act' not in gh_extensions.stdout"

    - name: update gh-act extension
      command: gh extension upgrade act
      register: gh_act_upgrade
      changed_when: true
      when:
        - "'nektos/gh-act' in gh_extensions.stdout"
        - "gh_act_release.json.tag_name not in gh_extensions.stdout"
