---
# renovate: datasource=github-tags depName=dyne/Tomb extractVersion=^v(?<version>.*)$
tomb_version: "2.9"
# sha256 of Tomb-{{ tomb_version }}.tar.gz; re-pin when bumping tomb_version
tomb_sha256: "b3a23c6680815f7557a3c4bd73d2b2dbde870a62357fcbf9b33089afae75d68c"
