- name: find latest release of dbxcli
  uri:
    url: https://api.github.com/repos/dropbox/dbxcli/releases/latest
  register: download

- set_fact:
    asset: "{{ download.json.assets | select('match', '.*linux-amd64') | first }}"

# get_url requires directory to exist
- name: ensure install directory exists
  file:
    state: directory
    path: $HOME/.local/bin

- name: download latest version of dbxcli
  get_url:
    url: "{{ asset.browser_download_url }}"
    dest: $HOME/.local/bin/dbxcli
    mode: "755"
    force: true
