- name: Install apt packages
  apt:
    name: make
    state: latest
    update_cache: yes

- name: clone pop shell repo
  git:
    repo: https://github.com/pop-os/shell.git
    dest: ./tmp/pop_shell
  register: pop_shell

- name: install pop shell
  when: pop_shell.changed
  make:
    chdir: ./tmp/pop_shell
    target: local-install
