---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Install handy .deb runtime dependencies
      apt:
        name:
          - libgtk-layer-shell0
        state: present
        update_cache: true
