- name: Install apt packages
  become: true
  apt:
    name:
      - cryptsetup
      - file
      - gnupg
      - make
      - pinentry-curses
      - sudo
      - zsh
    state: latest
    update_cache: true

- name: make temp dir
  tempfile:
    state: directory
  register: tmp_dir

- name: download tomb
  get_url:
    url: https://files.dyne.org/tomb/releases/Tomb-2.9.tar.gz
    dest: "{{ tmp_dir.path }}/tomb.tar.gz"
  register: tomb_file

- name: unzip tomb_file
  when: tomb_file.changed
  shell: tar xvfz ./tomb.tar.gz
  args:
    chdir: "{{ tmp_dir.path }}"

- name: run make
  when: tomb_file.changed
  make:
    chdir: "{{ tmp_dir.path }}/Tomb-2.9"
    target: install

- name: remove tmp dir
  file:
    path: "{{ tmp_dir.path }}"
    state: absent
