- name: Install apt packages
  become: true
  apt:
    name:
      - cryptsetup
      - file
      - gnupg
      - make
      - pinentry-curses
      - sudo
      - zsh
    state: latest
    update_cache: yes

- name: download tomb
  get_url:
    url: https://files.dyne.org/tomb/releases/Tomb-2.9.tar.gz
    dest: ./tmp/tomb.tar.gz
  register: tomb_file

- name: unzip tomb_file
  when: tomb_file.changed
  shell: tar xvfz ./tomb.tar.gz
  args:
    chdir: ./tmp

- name: run make
  when: tomb_file.changed
  make:
    chdir: ./tmp/Tomb-2.9
    target: install
