- name: check for ecsy command
  shell:
    cmd: which ecsy
  changed_when: false
  failed_when: result.rc != 0 and result.rc != 127
  register: result

- name: install ecsy
  when: result.stdout == ''
  block:
    - name: install ecsy
      get_url:
        url: https://github.com/oberd/ecsy/releases/download/v0.2.16/ecsy-v0.2.16-linux
        dest: $HOME/.local/bin/ecsy
        mode: "755"

    - name: Install apt packages
      become: true
      apt:
        name: awscli
        state: latest
        update_cache: true
