---
- name: Assert aws-cli supports this architecture
  assert:
    that: ansible_architecture == "x86_64"
    fail_msg: "aws role only supports x86_64 (got {{ ansible_architecture }})"

- name: Check if aws-cli is installed
  shell:
    cmd: which aws
  changed_when: false
  failed_when: result.rc != 0 and result.rc != 1
  register: result

- name: Install aws-cli
  when: result.rc == 1
  block:
    - name: Install apt packages
      become: true
      apt:
        name:
          - unzip
        state: latest
        update_cache: true

    - name: Make temp dir
      tempfile:
        state: directory
      register: tmp_dir

    - name: Download aws-cli v2 zip
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ aws_cli_version }}.zip"
        dest: "{{ tmp_dir.path }}/awscliv2.zip"
        checksum: "sha256:{{ aws_cli_sha256 }}"

    - name: Extract aws-cli
      unarchive:
        src: "{{ tmp_dir.path }}/awscliv2.zip"
        dest: "{{ tmp_dir.path }}"
        remote_src: true

    - name: Run aws-cli installer
      become: true
      command:
        cmd: "{{ tmp_dir.path }}/aws/install"
        creates: /usr/local/bin/aws
  always:
    - name: Remove tmp dir
      file:
        path: "{{ tmp_dir.path }}"
        state: absent
      when: tmp_dir.path is defined
