- name: find latest release of ecsy
  uri:
    url: https://api.github.com/repos/oberd/ecsy/releases/latest
  register: download

- set_fact:
    asset: "{{ download.json.assets | select('match', '.*linux') | first }}"

- name: download latest version of ecsy
  get_url:
    url: "{{ asset.browser_download_url }}"
    dest: $HOME/.local/bin/ecsy
    mode: "755"
    force: true
