- name: add enpass repository
  deb822_repository:
    name: enpass
    types: deb
    uris: https://apt.enpass.io/
    suites: stable
    components: main
    signed_by: https://apt.enpass.io/keys/enpass-linux.key
    install_python_debian: true

- name: Install apt packages
  apt:
    name: enpass
    state: latest
    update_cache: true
