#todo use tempfile
#todo check if chrome is installed first
- name: download chrome
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: ./tmp/chrome.deb
  register: chrome_file

- name: install chrome
  when: chrome_file.changed
  apt: deb="./tmp/chrome.deb"
