- name: check if dropbox is installed
  shell:
    cmd: which dropbox
  changed_when: false
  failed_when: result.rc != 0 and result.rc != 1
  register: result

- name: install dropbox
  when: result.rc == 1
  block:
    - name: make temp dir
      tempfile:
        state: directory
      register: tmp_dir

    - name: download dropbox deb
      get_url:
        url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
        dest: "{{ tmp_dir.path }}/dropbox.deb"
      register: dropbox_file
      retries: 5
      delay: 10
      until: dropbox_file.status_code < 400

    - name: add dropbox signing key
      get_url:
        url: https://www.linuxbabe.com/dropbox-signing-key.asc
        dest: /etc/apt/trusted.gpg.d/dropbox.asc
        mode: "644"

    - name: install dropbox
      apt: deb="{{ tmp_dir.path }}/dropbox.deb"

    - name: remove tmp dir
      file:
        path: "{{ tmp_dir.path }}"
        state: absent
