- name: Install required packages
  become: true
  apt:
    state: present
    name:
      - ca-certificates
      - fontconfig
      - xz-utils

- name: Download and extract fonts to fonts directory.
  include_tasks: "download-font.yml"
  loop: "{{ fonts }}"
  loop_control:
    loop_var: font

- name: Update font cache
  shell: fc-cache -f
  changed_when: false
