- name: check if jet is installed
  shell:
    cmd: which jet
  changed_when: false
  failed_when: result.rc != 0 and result.rc != 1
  register: result

- name: install jet
  when: result.rc == 1
  block:
    - name: make temp dir
      tempfile:
        state: directory
      register: tmp_dir

    - name: download jet
      get_url:
        url: https://s3.amazonaws.com/codeship-jet-releases/2.14.0/jet-linux_amd64_2.14.0.tar.gz
        dest: "{{ tmp_dir.path }}/jet.tar.gz"
      register: jet_file

    # unzip requires path to exist
    - name: ensure install directory exists
      file:
        state: directory
        path: $HOME/.local/bin

    - name: unzip jet
      unarchive:
        src: "{{ tmp_dir.path }}/jet.tar.gz"
        dest: $HOME/.local/bin
        mode: "755"

    - name: remove tmp dir
      file:
        path: "{{ tmp_dir.path }}"
        state: absent
