- name: add acli repository
  deb822_repository:
    name: acli
    types: deb
    uris: https://acli.atlassian.com/linux/deb
    suites: stable
    components: main
    signed_by: https://acli.atlassian.com/gpg/public-key.asc
    install_python_debian: true

- name: install acli
  apt:
    name: acli
    state: latest
    update_cache: true
