- name: install apt packages
  become: true
  apt:
    name:
      - universal-ctags
      - libfuse2
    state: latest
    update_cache: true

- name: register github api for neovim latest release
  uri:
    url: https://api.github.com/repos/neovim/neovim/releases/latest
  register: neovim

- name: download nvim appimage
  get_url:
    url: "{{ neovim|json_query('json.assets[?name == `nvim-linux-x86_64.appimage`].browser_download_url|[0]') }}"
    dest: $HOME/.local/bin/nvim
    mode: "755"

- name: install pip packages
  pip:
    name: pynvim
    state: latest
    executable: $HOME/.asdf/shims/pip

- name: install pip2 packages
  pip:
    name: pynvim
    state: latest
    executable: $HOME/.asdf/shims/pip2

- name: install ruby packages
  gem:
    name: neovim
    state: latest
    executable: $HOME/.asdf/shims/gem

- name: install node neovim package
  npm:
    name: "{{ item }}"
    global: true
    state: latest
    executable: $HOME/.asdf/shims/npm
  with_items:
    - neovim
    - yarn
    - tree-sitter-cli

- name: install cpan packages
  cpanm:
    name: "{{ item }}"
    notest: true
    executable: $HOME/.asdf/shims/cpanm
  with_items:
    - Neovim::Ext
    - App::cpanminus

- name: clone php debug client repo
  git:
    repo: https://github.com/xdebug/vscode-php-debug.git
    dest: $HOME/.local/lib/php-debug-client
  register: php_debug_client

- name: install deps for php debug client
  when: php_debug_client.changed
  npm:
    path: $HOME/.local/lib/php-debug-client

- name: build php debug client
  when: php_debug_client.changed
  args:
    chdir: $HOME/.local/lib/php-debug-client
  command: npm run build
