- name: Install apt packages
  become: true
  apt:
    name: universal-ctags
    state: latest
    update_cache: true

- name: Check current neovim version.
  shell: nvim --version | head -n 1
  failed_when: false
  changed_when: false
  register: nvim_current_version

- name: Check latest version of neovim
  uri:
    url: https://api.github.com/repos/neovim/neovim/releases/latest
  register: neovim

- name: make temp dir
  tempfile:
    state: directory
  register: tmp_dir

- name: Download nvim deb
  when: >
    nvim_current_version.stdout is defined
    and neovim.json.name|lower not in nvim_current_version.stdout|lower
  get_url:
    url: "{{ neovim|json_query('json.assets[?name == `nvim-linux64.deb`].browser_download_url|[0]') }}"
    dest: "{{ tmp_dir.path }}/neovim.deb"
    mode: "755"

- name: install neovim
  become: true
  apt: deb="{{ tmp_dir.path }}/neovim.deb"

- name: remove tmp dir
  file:
    path: "{{ tmp_dir.path }}"
    state: absent

- name: install pip packages
  pip:
    name: pynvim
    state: latest

- name: install pip2 packages
  pip:
    name: pynvim
    state: latest
    executable: pip2

- name: install ruby packages
  gem:
    name: neovim
    state: latest

- name: install node neovim package
  npm:
    name: neovim
    global: true
    state: latest

- name: clone php debug client repo
  git:
    repo: https://github.com/xdebug/vscode-php-debug.git
    dest: ./local/lib/php-debug-client
  register: php_debug_client

- name: install deps for php debug client
  when: php_debug_client.changed
  npm:
    path: ./local/lib/php-debug-client

- name: build php debug client
  when: php_debug_client.changed
  args:
    chdir: ./local/lib/php-debug-client
  command: npm run build
