- name: Install apt packages
  become: true
  apt:
    name: universal-ctags
    state: latest
    update_cache: true

- name: install nvim
  become: true
  block:
    - name: add neovim apt repository
      apt_repository:
        repo: ppa:neovim-ppa/stable
        state: present
        filename: neovim

    - name: Install apt packages
      apt:
        name: neovim
        state: latest
        update_cache: true

- name: install pip packages
  pip:
    name: pynvim
    state: latest

- name: install pip2 packages
  pip:
    name: pynvim
    state: latest
    executable: pip2

- name: install ruby packages
  gem:
    name: neovim
    state: latest

- name: install node neovim package
  npm:
    name: neovim
    global: true
    state: latest

- name: clone php debug client repo
  git:
    repo: https://github.com/xdebug/vscode-php-debug.git
    dest: $HOME/.local/lib/php-debug-client
  register: php_debug_client

- name: install deps for php debug client
  when: php_debug_client.changed
  npm:
    path: $HOME/.local/lib/php-debug-client

- name: build php debug client
  when: php_debug_client.changed
  args:
    chdir: $HOME/.local/lib/php-debug-client
  command: npm run build
